services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres 
    ports:
      - 5432:5432
    volumes:
      - postgres_db:/var/lib/postgresql/data
    networks:
      - apiNetwork
  app:
    image: my-app
    port:
      - 9000:9000
    depends_on:
      - db
    

