services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5433:5432
    volumes:
      - postgres_db:/var/lib/postgresql/data
    networks:
      - apiNetwork
  # app:
  #   image: my-app
  #   port:
  #     - 9000:9000
  #   depends_on:
  #     - db

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - 5050:80
    volumes:
     - pgadmin_data:/var/lib/pgadmin
    networks:
     - apiNetwork

volumes:
  postgres_db:
  pgadmin_data:

networks:
 apiNetwork: